[workspace]

members = [
  "examples/spawn-chain",
  "examples/interpreter-in-browser",
  "lumen",
  "lumen_runtime",
  "lumen_runtime_macros",
  "liblumen_arena",
  "liblumen_alloc",
  "liblumen_alloc_macros",
  "liblumen_beam",
  "liblumen_compiler",
  "liblumen_core",
  "liblumen_eir_interpreter",
  "lumen_web",
]

[profile.release]
# Experimentally determined to give the smallest size out of all `opt-level`s (0-3,'s','z') and
# `lto`s (true and false) for `examples/spawn-chain/pkg/spawn_chaing_bg.wasm`
opt-level = 2
lto = false
