[package]
name = "lumen"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
readme = "README.md"
publish = false
edition = "2018"

[dependencies]
clap = "2.32.0"
human-panic = "1.0"
anyhow = "1.0.11"
thiserror = "1.0.1"
libeir_diagnostics = { git = "https://github.com/eirproject/eir.git" }
liblumen_compiler = { path = "../liblumen_compiler" }
